from pathlib import Path
import json, hashlib, shutil
B=Path(__file__).resolve().parent; V2=B if (B/'app/v02').exists() else Path('/data/oratorio_v02'); O=B/'app/v03'; O.mkdir(parents=True,exist_ok=True)
for f in (V2/'app/v02').iterdir():
 if f.is_file(): shutil.copy2(f,O/f.name)
if (V2/'app/assets').resolve()!=(B/'app/assets').resolve():
 shutil.copytree(V2/'app/assets',B/'app/assets',dirs_exist_ok=True)
SRC=B/'source/narrative-v03'
lines=(SRC/'01.txt').read_text().splitlines()
inventory=json.loads((SRC/'inventory.json').read_text())[0]
def quote(lo,hi=None):
 return {'text':'\n'.join(lines[lo-1:(hi or lo)]),'lines':[lo,hi or lo]}
def after(label,a,b):
 ix=next(i for i in range(a-1,b) if lines[i]==label); return quote(ix+2)
starts=[next(i+1 for i,s in enumerate(lines) if s.startswith('CUE-N01-01:')),next(i+1 for i,s in enumerate(lines) if s.startswith('CUE-N01-02:')),next(i+1 for i,s in enumerate(lines) if s.startswith('CUE-N02-01:'))]
data={'schemaVersion':1,'status':'CANDIDATE_ONLY','autoFollow':False,'source':{'id':'N01-03-v02','version':'v02','fileName':inventory['name'],'docxSha256':inventory['file_sha256'],'textSha256':inventory['text_sha256'],'archiveSha256':'f3269b9693521bbaf3563fd92fbd5da795d2c0a791d2eb5abafd1ccd3e5f2a84','registry':'https://app.notion.com/p/3dfc9e66576681a4ba9cc5b3be2934de','sourceText':'source-no01-03.txt'},'arc':[{'label':s,'piece':p} for s,p in [('고립','No.1'),('계시','No.1'),('명령','No.2'),('위로','No.3'),('신비','No.3')]],'stages':[]}
for i,(sid,label,m,pg,nline,aline) in enumerate([('isolation','고립',[1,13],[7,8],27,25),('revelation','계시',[14,21],[8],38,36)]):
 a,b=starts[i],starts[i+1]-1
 data['stages'].append({'id':sid,'label':label,'pieceId':'NO01','cueId':f'CUE-N01-0{i+1}','measureRange':m,'printedPages':pg,'narrative':quote(nline),'music':quote(aline),'singing':after('Singing:',a,b),'risk':after('Risk:',a,b),'theology':after('Theology:',a,b),'cueTitle':lines[a-1].split(': ',1)[1],'rawCue':quote(a,b),'normalizedRect':None,'timeRange':None,'mappingStatus':'UNVERIFIED','emotionStatus':'NOT_SEPARATELY_PROVIDED'})
content=json.loads((V2/'app/v02/data/content-v01.json').read_text());content['config']['build']='unified-internal-v0.3.0';content['narrativeReview']=data
(O/'data').mkdir(exist_ok=True)
(O/'data/content-v01.json').write_text(json.dumps(content,ensure_ascii=False,separators=(',',':')))
(O/'source-no01-03.txt').write_bytes((SRC/'01.txt').read_bytes())
(O/'bundle.js').write_text('window.ORATORIO_BASELINE='+json.dumps(content,ensure_ascii=False,separators=(',',':')).replace('</',r'<\/')+';')
package=json.loads((V2/'app/v02/package.json').read_text());package['version']='0.3.0-data.1';package['scope']='내부 서사 수동 탐색 검증 · 자동 동기화 아님'
p=O/'data/content-v01.json';package['items'][0].update(bytes=p.stat().st_size,sha256=hashlib.sha256(p.read_bytes()).hexdigest())
(O/'package.json').write_text(json.dumps(package,ensure_ascii=False,indent=2))
js=(V2/'app/v02/app.js').read_text().replace('내부 검증본 v0.2','내부 검증본 v0.3')
js=js.replace("function practice(){", "let practiceMode='midi',narrativeStage='isolation';\nconst N=window.ORATORIO_BUNDLE.narrativeReview;\nfunction practice(){")
js=js.replace('<div class="practice-meta">', '${n?modeSwitcher():\'\'}<div class="practice-meta">')
js=js.replace('updateTransport();window.OratorioOffline.refreshSummary();}', 'updateTransport();window.OratorioOffline.refreshSummary();attachNarrative();}')
js=js.replace("if(b.dataset.route){", "if(b.dataset.mode){setMode(b.dataset.mode);return;}if(b.dataset.narrativeStage){narrativeStage=b.dataset.narrativeStage;renderNarrative();document.querySelector('[data-narrative-stage=\"'+narrativeStage+'\"]')?.focus({preventScroll:true});return;}if(b.dataset.narrativeAction){if(b.dataset.narrativeAction==='open'){openNarrative(b);}if(b.dataset.narrativeAction==='close')$('#narrative-dialog').close();return;}\nif(b.dataset.route){")
js=js.replace('window.__oratorioReview={state,', 'window.__oratorioReview={state,get practiceMode(){return practiceMode;},get narrativeStage(){return narrativeStage;},get playGeneration(){return playGeneration;},')
functions=r'''
function modeSwitcher(){return `<div class="mode-switch" role="group" aria-label="악보 모드"><button data-mode="midi" aria-pressed="${practiceMode==='midi'}">MIDI 연습</button><button data-mode="narrative" aria-pressed="${practiceMode==='narrative'}">서사 악보 · 음악 포함</button></div>`;}
const selectedStage=()=>N.stages.find(s=>s.id===narrativeStage)||N.stages[0];
function sourceQuote(q){return `<blockquote>${esc(q.text)}</blockquote><p class="caption source-line">원문 L${q.lines[0]}${q.lines[1]!==q.lines[0]?'–'+q.lines[1]:''} · 후보</p>`;}
function narrativeMarkup(){const s=selectedStage();return `<header><p class="eyebrow">서사 악보 · 수동 탐색</p><h3 id="narrative-heading">${esc(s.label)} <span class="tag">원문 후보</span></h3><p class="caption">${s.measureRange[0]}–${s.measureRange[1]}마디 · 원문 표기, 대응 검증 대기</p></header><nav class="arc-strip" aria-label="서사 단계">${N.arc.map((a,i)=>i<2?`<button data-narrative-stage="${N.stages[i].id}" aria-pressed="${s.id===N.stages[i].id}" class="${s.id===N.stages[i].id?'selected':''}">${esc(a.label)}<small>${a.piece}</small></button>`:`<span class="arc-context">${esc(a.label)}<small>${a.piece}</small></span>`).join('')}</nav><p class="caption mapping-warning">정보 선택은 음악 위치를 바꾸지 않습니다. 자동 따라가기는 연결 검증 전입니다.</p><section class="interpret-layer"><h4>서사</h4>${sourceQuote(s.narrative)}</section><section class="interpret-layer"><h4>감정·서사 전환</h4><p class="transition-flow"><span>고립</span><span aria-hidden="true">→</span><span>계시</span></p><p class="caption">원문 서사 아크입니다. 별도의 감정 전환 문안은 미기재이며 새 감정 지시를 추가하지 않았습니다.</p></section><section class="interpret-layer"><details><summary>가창 지시 <span>원문 제안</span></summary>${sourceQuote(s.singing)}<p class="caption">원문 [PROPOSAL] 인용이며 승인된 발성 처방이 아닙니다.</p></details></section><section class="interpret-layer"><details><summary>주의점 <span>원문 메모</span></summary>${sourceQuote(s.risk)}</details></section><section class="interpret-layer"><details><summary>음악적 근거 <span>대조 전</span></summary>${sourceQuote(s.music)}<p class="caption">원문의 [FACT] 표기는 실제 악보 검증 완료를 뜻하지 않습니다.</p></details></section><div class="narrative-actions"><button class="secondary" data-narrative-action="open">Cue 원문·근거 자세히</button><button disabled title="재생 시간 연결이 검증되지 않았습니다.">이 전환 반복 · 연결 대기</button></div><p class="caption">음악은 기존 플레이어에서 듣고 반복합니다. 원문 ${s.printedPages.join('–')}쪽 / 표시 악보 7쪽${s.id==='revelation'?' · 계시 대응 악보 미포함':''}.</p>`;}
function renderNarrative(){if($('#narrative-panel'))$('#narrative-panel').innerHTML=narrativeMarkup();}
function openNarrative(button){const s=selectedStage(),d=$('#narrative-dialog');if(!d)return;d.innerHTML=`<div class="sheet-head"><div><p class="eyebrow">${s.cueId} · CANDIDATE</p><h2 id="narrative-dialog-title">${esc(s.cueTitle)}</h2></div><button data-narrative-action="close" aria-label="원문 패널 닫기">닫기</button></div><p class="caption">원문 그대로 표시합니다. 악보·성부·시간축 대조와 해석 승인은 별개입니다.</p><pre class="source-full">${esc(s.rawCue.text)}</pre><details class="source-evidence"><summary>출처·버전·발췌 위치</summary><p>출처: N01–03 · Gemini 납품 v02<br>발췌: 원문 L${s.rawCue.lines.join('–')}<br>DOCX SHA-256: <code>${N.source.docxSha256}</code><br>텍스트 SHA-256: <code>${N.source.textSha256}</code></p><a href="${esc(N.source.registry)}" target="_blank" rel="noopener noreferrer">서사 원본 접수대장</a> · <a href="source-no01-03.txt" target="_blank" rel="noopener noreferrer">전체 원문 텍스트</a></details>`;d._opener=button;d.onclose=()=>{if(d._opener?.isConnected)d._opener.focus({preventScroll:true});};d.showModal();}
function setMode(mode){if(!['midi','narrative'].includes(mode)||!$('#narrative-panel'))return;practiceMode=mode;$('#app').classList.toggle('narrative-view',mode==='narrative');$('#narrative-panel').hidden=mode!=='narrative';document.querySelectorAll('[data-mode]').forEach(b=>{const active=b.dataset.mode===mode;b.setAttribute('aria-pressed',String(active));b.classList.toggle('selected',active);});}
function attachNarrative(){if(state.screen!=='practice'||state.song!=='NO01'||!N)return;const practice=$('.practice'),workspace=document.createElement('div');workspace.className='narrative-workspace';const col=document.createElement('div');col.className='narrative-score-column';const meta=$('.practice-meta');meta.before(workspace);for(const el of [meta,$('#score-frame'),$('.score-note'),$('.control-bar')])col.append(el);workspace.append(col);const panel=document.createElement('aside');panel.id='narrative-panel';panel.className='narrative-panel';panel.setAttribute('aria-labelledby','narrative-heading');workspace.append(panel);const dialog=document.createElement('dialog');dialog.id='narrative-dialog';dialog.setAttribute('aria-labelledby','narrative-dialog-title');practice.append(dialog);renderNarrative();setMode(practiceMode);}
'''
js=js.replace("if(state.part!=='none'){state.screen='home';",functions+"\nif(state.part!=='none'){state.screen='home';")
(O/'app.js').write_text(js)
css=(V2/'app/v02/styles.css').read_text()+r'''
/* v0.3 internal narrative proposal; canonical UI JSON remains unchanged. */
.mode-switch{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:20px 0 16px}.mode-switch button[aria-pressed=true]{background:var(--navy);color:var(--surface);border-color:var(--navy)}
.narrative-workspace,.narrative-score-column{min-width:0}.narrative-panel{background:var(--surface);border:1px solid var(--line);border-top:3px solid var(--gold-line);border-radius:6px;padding:22px;margin-top:22px;font-size:16px;line-height:1.65}.narrative-panel h3{font:25px/1.5 var(--display);margin:6px 0}.narrative-panel h3 .tag{font:14px/1.5 var(--sans);vertical-align:middle}.arc-strip{display:flex;gap:6px;flex-wrap:wrap;margin:16px 0}.arc-strip>*{flex:1;min-width:52px;text-align:center;font-size:15px;line-height:1.4;padding:8px 4px}.arc-strip small{display:block;font-size:14px;font-weight:400;margin-top:4px}.arc-context{color:var(--muted);border:1px solid var(--line);border-radius:6px;background:var(--raised)}.interpret-layer{border-top:1px solid var(--line);padding-top:12px;margin-top:12px}.interpret-layer h4{font-size:16px;color:var(--gold);margin:0 0 8px}.interpret-layer blockquote{margin:0;font-size:16px;line-height:1.75;color:var(--ink);overflow-wrap:anywhere}.source-line{font-size:14px;margin-bottom:0}.transition-flow{display:flex;gap:12px;align-items:center;font-weight:700;margin:0}.interpret-layer summary{cursor:pointer;min-height:48px;align-content:center;color:var(--gold);font-weight:700;line-height:1.6}.interpret-layer summary span{font-size:14px;font-weight:400;color:var(--muted);margin-left:8px}.narrative-actions{display:grid;gap:8px;margin-top:16px}.narrative-actions button{font-size:15px}.mapping-warning{background:var(--raised);border-left:3px solid var(--gold-line);padding:8px 12px}.source-full{white-space:pre-wrap;overflow-wrap:anywhere;font:16px/1.8 var(--sans);padding:16px;background:var(--raised);border-radius:6px}.source-evidence{font-size:14px;overflow-wrap:anywhere;border-top:1px solid var(--line);padding-top:12px}.source-evidence summary{cursor:pointer;min-height:48px;align-content:center}.source-evidence code{overflow-wrap:anywhere}.source-evidence a{color:var(--gold)}#narrative-dialog{width:min(740px,calc(100% - 32px));max-height:calc(100dvh - 48px)}#narrative-dialog h2{font-size:24px}#narrative-dialog .sheet-head>div{min-width:0}#narrative-dialog .sheet-head button{flex-shrink:0}.narrative-view .score-frame{height:clamp(260px,35dvh,500px)}
@media(min-width:1180px){.app-shell.wide.narrative-view{max-width:1360px}.narrative-view .narrative-workspace{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(340px,1fr);gap:24px;align-items:start}.narrative-panel{margin-top:14px}.narrative-view .practice-heading h2{font-size:23px}.narrative-view .score-frame{height:clamp(270px,35dvh,450px)}}
@media(max-width:767px){.mode-switch button{font-size:14px;padding:8px}.narrative-panel{padding:18px}.narrative-panel h3{font-size:23px}.narrative-view .narrative-score-column{display:flex;flex-direction:column}.source-full{padding:12px}#narrative-dialog{padding:18px}#narrative-dialog h2{font-size:20px}.arc-strip small{font-size:14px}}
'''
css+='''\n.narrative-view .narrative-score-column{display:flex;flex-direction:column}.narrative-view .control-bar{order:0;margin-top:14px}.narrative-view .practice-meta{order:1}.narrative-view .score-frame{order:2}.narrative-view .score-note{order:3}.narrative-view .score-large{height:auto;max-height:600px}.mode-switch button,.arc-strip button,[data-narrative-action]{-webkit-tap-highlight-color:transparent}\n'''
(O/'styles.css').write_text(css)
for f in ['offline.js','sw.js']:
 t=(O/f).read_text().replace('oratorio-v02','oratorio-v03').replace('shell-0.2.0','shell-0.3.0')
 if f=='offline.js':t=t.replace("content:'악보·Cue·후보 시간축 데이터'","content:'악보·서사·Cue·후보 시간축 데이터'")
 # Source text is part of the shell: exact text is separately hashed in narrative provenance.
 t=t.replace("'icon-512.png']","'icon-512.png','source-no01-03.txt']")
 (O/f).write_text(t)
t=(O/'boot.js').read_text().replace('0.2.0-data.1','0.3.0-data.1');(O/'boot.js').write_text(t)
t=(O/'index.html').read_text().replace('내부 검증본 v0.2','내부 검증본 v0.3');(O/'index.html').write_text(t)
m=json.loads((O/'manifest.webmanifest').read_text());m['name']='오라토리오 리허설 · 서사 내부 검증본 v0.3';m['short_name']='서사 검증';(O/'manifest.webmanifest').write_text(json.dumps(m,ensure_ascii=False,indent=2))
manifest=[{'path':str(p.relative_to(B)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(O.rglob('*')) if p.is_file()]
(B/'v03-file-manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2))
print('v0.3 built:',len(manifest),'app files; 2 original stages and cues; 6 package items; v0.2 untouched.')
