from pathlib import Path
import json,hashlib
b=Path(__file__).resolve().parent; app=b/'app'; out=app/'v02'
config=json.loads((app/'data/integration.json').read_text());copy=json.loads((app/'data/copy.json').read_text())
config['build']='unified-internal-v0.2.0'; config['status']='INTERNAL_REVIEW_ONLY'
content={'config':config,'copy':copy}
(out/'data/content-v01.json').write_text(json.dumps(content,ensure_ascii=False,separators=(',',':')))
items=[]
for key,info in config['assets'].items():
 p=app/info['path'];items.append({'key':key,'url':'../'+info['path'],'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'mime':'audio/mpeg' if p.suffix=='.mp3' else 'image/png'})
p=out/'data/content-v01.json';items.insert(0,{'key':'content','url':'data/content-v01.json','bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'mime':'application/json'})
package={'schemaVersion':1,'id':'internal-no01-laodicea','version':'0.2.0-data.1','label':'No.1 · 테너·피아노 / 라오디게아 악보·해설','canonical':False,'scope':'내부 검증 자료 · 제1부 전체 아님','items':items}
(out/'package.json').write_text(json.dumps(package,ensure_ascii=False,indent=2))
(out/'bundle.js').write_text('window.ORATORIO_BASELINE='+json.dumps(content,ensure_ascii=False,separators=(',',':')).replace('</',r'<\/')+';')
js=(app/'app.js').read_text()
js=js.replace("if(!A[k]?.startsWith('data:audio/'))throw Error('실제 음원 데이터가 없습니다.');", "if(!A[k])throw Error('실제 음원 데이터가 없습니다.');")
js=js.replace('const data=await (await fetch(A[k])).arrayBuffer();', "const response=await fetch(A[k]);if(!response.ok)throw Error('음원 파일을 불러오지 못했습니다.');const data=await response.arrayBuffer();")
js=js.replace('내부 검증본 v0.1','내부 검증본 v0.2')
js=js.replace('<nav class="app-nav"', '<button class="library-shortcut full" data-action="library">내 자료함 · <span data-offline-summary>확인 중</span></button><nav class="app-nav"')
js=js.replace("case 'play':", "case 'library':window.OratorioOffline.open();break;case 'play':")
js=js.replace('이 검증본은 악보·음원 데이터를 파일에 포함합니다. 전체 제1부 다운로드 기능은 아직 구현하지 않았습니다.', '내 자료함에서 검증 자료를 저장하면 오프라인으로 다시 열 수 있습니다. 제1부 전체 자료는 아직 연결되지 않았습니다.')
js=js.replace('updateTransport();}\n$(\'#app\').addEventListener', "updateTransport();window.OratorioOffline.refreshSummary();}\n$('#app').addEventListener")
# Correct the daily label; do not erase or reinterpret existing cumulative records.
js=js.replace("${txt('practice','repeatCount')} ${state.counts[key()]||0}회", "누적 반복 ${state.counts[key()]||0}회")
js=js.replace("$('#app').setAttribute('data-screen',active);updateTransport();}","$('#app').setAttribute('data-screen',active);updateTransport();window.OratorioOffline.refreshSummary();}")
(out/'app.js').write_text(js)
css=(app/'styles.css').read_text()
css+='''\n/* v0.2 internal proposal: download/library status, no new visual identity. */
.library-shortcut{margin-bottom:12px;text-align:left;background:var(--raised);font-size:16px}.library-shortcut span{color:var(--muted)}
#offline-dialog{width:min(720px,calc(100% - 32px));padding:24px}#offline-dialog h2{font-size:26px}.library-meta{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.library-status{padding:8px 12px;border:1px solid var(--line);border-radius:6px;background:var(--raised);font-size:15px}.library-status[data-ready=true]{color:#315E37;border-color:#8BA98B;background:#EDF4E8}.library-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:20px 0}.library-actions .primary{grid-column:1/-1}.library-files{display:grid;gap:8px;margin:16px 0}.library-files li{display:flex;justify-content:space-between;gap:12px;list-style:none;border-bottom:1px solid var(--line);padding-bottom:8px;font-size:15px}.library-files{padding:0}#download-progress{width:100%;height:14px;accent-color:var(--gold)}#library-error{overflow-wrap:anywhere}.storage-meter{font-size:14px}.library-detail{font-size:15px;line-height:1.7}.library-detail h3{font-size:18px}.library-detail p{margin-bottom:12px}.library-warning{border-left:3px solid var(--gold-line);padding-left:12px;color:var(--muted);font-size:14px}.install-row{margin-top:20px;border-top:1px solid var(--line);padding-top:16px}.library-files span:last-child{white-space:nowrap}.caption,.eyebrow,.review-banner,.practice-status{font-size:14px}@media(max-width:767px){:root{--body:16px}.library-actions{grid-template-columns:1fr}.library-actions .primary{grid-column:auto}#offline-dialog{padding:20px}.library-files li{font-size:14px;align-items:flex-start}.library-shortcut{font-size:15px}}
'''
(out/'styles.css').write_text(css)
html='''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><meta name="theme-color" content="#F1EBDE"><meta name="apple-mobile-web-app-capable" content="yes"><title>오라토리오 · 내부 검증본 v0.2 · 오프라인 자료함</title><link rel="manifest" href="manifest.webmanifest"><link rel="icon" href="icon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="icon-192.png"><link rel="stylesheet" href="styles.css"></head><body><p class="orientation">태블릿을 세로로 세우시면 악보가 크게 보입니다. 가로로도 보실 수 있습니다.</p><p id="storage-notice" class="global-notice" hidden>저장 기능을 사용할 수 없습니다. 이 창에서만 기록이 유지됩니다.</p><p id="phone-notice" class="global-notice phone-notice" hidden>스마트폰은 음원 청취 보조용입니다. 악보 연습은 태블릿을 권합니다.</p><main id="app" class="app-shell"><h1>오라토리오 · 내부 검증본 v0.2</h1><p>검증 자료를 확인하고 있습니다.</p></main><p id="toast" role="status" hidden></p><dialog id="offline-dialog" aria-labelledby="library-title"><div class="sheet-head"><div><p class="eyebrow">저장 · 오프라인 · 안전한 수정본</p><h2 id="library-title">내 자료함</h2></div><button id="library-close" aria-label="자료함 닫기">닫기</button></div><p class="library-warning">현재 저장 대상은 두 검증 사례입니다. 전체 제1부·모든 파트 자료나 정본 음원이 아닙니다.</p><div class="library-meta"><span id="library-state" class="library-status" role="status"></span><span id="network-state" class="library-status"></span></div><div class="library-detail"><h3>No.1 · 테너·피아노<br>라오디게아 · 악보와 해설</h3><p id="library-version"></p><p id="library-space" class="storage-meter"></p></div><progress id="download-progress" max="100" value="0" aria-label="검증 자료 저장 진행률"></progress><p id="library-progress" class="caption" aria-live="polite"></p><ul id="library-files" class="library-files"></ul><p id="library-error" class="error" role="alert" hidden></p><div class="library-actions"><button id="package-save" class="primary">검증 자료 저장</button><button id="package-apply" class="primary" hidden>저장한 자료 적용 · 새로고침</button><button id="package-check">수정본 확인</button><button id="package-rollback">이전 자료로 복구</button><button id="storage-persist">자료 보관 요청</button><button id="package-delete">저장 자료 삭제</button></div><p class="caption">새 자료는 별도로 검증한 뒤 교체합니다. 실패하면 기존 자료를 유지합니다. 자료 삭제는 연습 기록을 지우지 않습니다.</p><div class="install-row"><h3>다시 열기</h3><button id="install-app" class="full" hidden>홈 화면에 앱 설치</button><p id="install-help" class="caption">지원 브라우저의 메뉴에서 ‘설치’ 또는 ‘홈 화면에 추가’를 선택하세요. 저장 완료 후 인터넷을 끊고 이 주소를 다시 열어 확인합니다.</p><p id="persistence-note" class="caption">브라우저 데이터 삭제·기기 저장 공간 부족으로 자료가 사라질 수 있습니다. 보관 요청은 브라우저가 허용할 때만 적용됩니다.</p></div></dialog><noscript>이 앱은 JavaScript가 필요합니다.</noscript><script src="bundle.js"></script><script src="offline.js"></script><script src="boot.js"></script></body></html>'''
(out/'index.html').write_text(html)
(out/'manifest.webmanifest').write_text(json.dumps({'id':'./','name':'오라토리오 리허설 · 내부 검증본','short_name':'오라토리오 검증','start_url':'./','scope':'./','display':'standalone','background_color':'#F1EBDE','theme_color':'#F1EBDE','icons':[{'src':f'icon-{n}.png','sizes':f'{n}x{n}','type':'image/png','purpose':'any'} for n in [192,512]]},ensure_ascii=False,indent=2))
(out/'icon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><rect width="512" height="512" rx="72" fill="#111726"/><path d="M176 332V148L350 116V300" fill="none" stroke="#C9AE6E" stroke-width="28"/><ellipse cx="145" cy="343" rx="50" ry="35" fill="#C9AE6E"/><ellipse cx="319" cy="311" rx="50" ry="35" fill="#C9AE6E"/></svg>')
print('v0.2 shell & verified package manifest built:', len(items),'files;',sum(i['bytes'] for i in items),'package bytes')
