const {chromium}=require('/vercel/sandbox/node_modules/playwright');
const fs=require('fs'),assert=require('assert'),crypto=require('crypto');
const ROOT='/data/oratorio_v03',BASE='http://localhost:8774/app/v03/';
const results=[],errors=[];const check=(name,ok)=>{assert(ok,name);results.push({name,status:'PASS'});};
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/local/bin/chromium',headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1180,height:820},hasTouch:true});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(BASE);await page.waitForFunction(()=>!!window.__oratorioReview);
 await page.locator('[data-part="T"]').click();await page.locator('#first-next').click();await page.locator('[data-open="NO01"]').click();await page.locator('section [data-route="practice"]').click();
 check('기존 MIDI 모드로 시작',await page.evaluate(()=>__oratorioReview.practiceMode==='midi')&&await page.locator('#narrative-panel').isHidden());
 await page.locator('#play').click();await page.waitForFunction(()=>__oratorioReview.playing);await page.waitForTimeout(300);
 const before=await page.evaluate(()=>({pos:__oratorioReview.position,gen:__oratorioReview.playGeneration,track:__oratorioReview.state.track,from:__oratorioReview.state.from,to:__oratorioReview.state.to,speed:__oratorioReview.state.speed}));
 await page.locator('[data-mode="narrative"]').tap();
 const after=await page.evaluate(()=>({pos:__oratorioReview.position,gen:__oratorioReview.playGeneration,playing:__oratorioReview.playing,sources:__oratorioReview.sourceCount}));
 check('서사 모드 전환 후 음악 유지',after.playing&&after.sources===2&&after.gen===before.gen);
 check('모드 전환으로 재생 위치 초기화하지 않음',after.pos>=before.pos&&after.pos-before.pos<2);
 check('트랙·속도·루프 구간 유지',await page.evaluate(b=>__oratorioReview.state.track===b.track&&__oratorioReview.state.speed===b.speed&&__oratorioReview.state.from===b.from&&__oratorioReview.state.to===b.to,before));
 check('원문 네 레이어 표시',await page.locator('#narrative-panel .interpret-layer').count()===5);
 check('두 No1 단계만 조작 가능',await page.locator('[data-narrative-stage]').count()===2&&await page.locator('.arc-context').count()===3);
 check('검증 전 Cue 반복 버튼 잠금',await page.locator('.narrative-actions button[disabled]').isDisabled());
 await page.locator('[data-narrative-stage="revelation"]').tap();
 check('다른 서사 읽어도 음악 위치·세대 유지',await page.evaluate(g=>__oratorioReview.playing&&__oratorioReview.playGeneration===g&&__oratorioReview.state.from===1&&__oratorioReview.state.to===3,before.gen));
 check('8쪽 대응 악보 미포함 명시',await page.locator('#narrative-panel').textContent().then(t=>t.includes('계시 대응 악보 미포함')));
 check('감정 문안 임의 생성하지 않음',await page.locator('#narrative-panel').textContent().then(t=>t.includes('별도의 감정 전환 문안은 미기재')));
 await page.locator('[data-narrative-action="open"]').tap();
 check('터치로 원문 팝업 열림',await page.locator('#narrative-dialog').evaluate(d=>d.open));
 check('팝업 열기 중 MIDI 계속 재생',await page.evaluate(g=>__oratorioReview.playing&&__oratorioReview.playGeneration===g,before.gen));
 check('원문 Cue ID 정확히 연결',await page.locator('#narrative-dialog').textContent().then(t=>t.includes('CUE-N01-02')&&!t.includes('CUE-N01-01:')));
 await page.waitForTimeout(250);await page.screenshot({path:ROOT+'/qa/narrative-dialog-landscape.png'});
 await page.keyboard.press('Escape');check('Escape 닫기·초점 복귀',await page.locator('#narrative-dialog').evaluate(d=>!d.open)&&await page.evaluate(()=>document.activeElement.dataset.narrativeAction==='open'));
 await page.locator('[data-mode="midi"]').tap();check('MIDI 모드 복귀도 음악 재시작 없음',await page.evaluate(g=>__oratorioReview.playing&&__oratorioReview.playGeneration===g,before.gen));
 await page.locator('[data-mode="narrative"]').tap();await page.locator('#play').click();
 await page.locator('[data-narrative-stage="isolation"]').tap();
 const narrative=JSON.parse(fs.readFileSync(ROOT+'/app/v03/data/content-v01.json')).narrativeReview;
 const source=fs.readFileSync(ROOT+'/app/v03/source-no01-03.txt'),lines=source.toString().split(/\r?\n/);
 check('DOCX 추출 원문 텍스트 해시 일치',crypto.createHash('sha256').update(source).digest('hex')===narrative.source.textSha256);
 check('모든 화면 발췌가 원문 위치와 정확히 일치',narrative.stages.every(s=>['narrative','music','singing','risk','theology','rawCue'].every(k=>s[k].text===lines.slice(s[k].lines[0]-1,s[k].lines[1]).join('\n'))));
 check('미확인 좌표·시간을 비워 둠',narrative.stages.every(s=>s.normalizedRect===null&&s.timeRange===null)&&narrative.autoFollow===false);
 for(const [w,h] of [[1180,820],[820,1180],[390,844]]){
  await page.setViewportSize({width:w,height:h});await page.waitForTimeout(80);
  check(`${w}×${h} 서사 화면 가로 넘침 없음`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  check(`${w}×${h} 터치 버튼 44px 이상`,await page.locator('[data-mode], [data-narrative-stage], [data-narrative-action="open"]').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=44&&e.getBoundingClientRect().width>=44)));
  await page.screenshot({path:ROOT+`/qa/narrative-${w}x${h}.png`,fullPage:true});
  await page.locator('[data-narrative-action="open"]').tap();
  check(`${w} 팝업이 화면 폭 안에 표시`,await page.locator('#narrative-dialog').evaluate(d=>{const r=d.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;}));
  await page.waitForTimeout(250);if(w!==1180)await page.screenshot({path:ROOT+`/qa/narrative-dialog-${w}.png`});
  await page.locator('[data-narrative-action="close"]').tap();
 }
 await page.setViewportSize({width:1180,height:820});await page.evaluate(()=>window.scrollTo(0,0));
 await page.evaluate(()=>{for(const d of document.querySelectorAll('#narrative-panel details'))d.open=true;});
 await page.screenshot({path:ROOT+'/qa/narrative-expanded.png',fullPage:true});
 // A static snapshot for the mandatory bundled capture helper: actual rendered markup, no invented source.
 const snapshot=await page.evaluate(()=>document.documentElement.outerHTML);
 let html=snapshot.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<link[^>]*rel="(?:manifest|icon|apple-touch-icon)"[^>]*>/gi,'').replace(/<link[^>]*href="styles.css"[^>]*>/,'<style>'+fs.readFileSync(ROOT+'/app/v03/styles.css','utf8')+'</style>');
 html=html.replace(/src="http:\/\/localhost:8774\/app\/assets\/([^"?]+)[^"]*"/g,(_,p)=>`src="data:image/png;base64,${fs.readFileSync(ROOT+'/app/assets/'+p).toString('base64')}"`);
 fs.writeFileSync(ROOT+'/qa/narrative-preview.html',html);
 await page.locator('[data-action="library"]').click();await page.locator('#package-save').click();await page.waitForFunction(()=>!OratorioOffline.busy&&OratorioOffline.activeValid);await page.locator('#library-close').click();
 await context.setOffline(true);check('네트워크 차단 실제 확인',await page.evaluate(async()=>{try{await fetch('package.json?uncached='+Date.now());return false;}catch{return true;}}));
 await page.reload();await page.waitForFunction(()=>!!window.__oratorioReview);await page.locator('[data-action="resume"]').click();await page.locator('[data-mode="narrative"]').click();
 check('오프라인 재실행에서 서사 데이터 열람',await page.locator('#narrative-panel').textContent().then(t=>t.includes('고립'))&&await page.evaluate(()=>ORATORIO_BUNDLE.narrativeReview.stages.length===2));
 await page.locator('[data-narrative-action="open"]').click();await page.locator('[data-narrative-action="close"]').click();await page.locator('#play').click();await page.waitForFunction(()=>__oratorioReview.playing);
 check('오프라인 서사 모드 실제 음악 재생',await page.evaluate(()=>__oratorioReview.audioDecoded&&__oratorioReview.sourceCount===2));await page.locator('#play').click();
 check('새 기능 브라우저 예외 없음',errors.length===0);
 fs.writeFileSync(ROOT+'/qa/narrative-report.json',JSON.stringify({testedAt:new Date().toISOString(),environment:'Chromium touch-enabled emulator; localhost; not physical tablet',tests:results,errors,excluded:['actual iPad/Safari and Android','musical listening approval','automatic narrative synchronization','new No1 measure hotspots']},null,2));
 console.log(JSON.stringify({passed:results.length,errors}));await browser.close();process.exit(0);
})().catch(e=>{console.error(e.stack);process.exit(1)});
