const {chromium}=require('/vercel/sandbox/node_modules/playwright');const fs=require('fs'),assert=require('assert');const ROOT='/data/oratorio_v04',URL='https://gilhajeong.github.io/notion/app/v04/',tests=[],errors=[];const check=(name,ok)=>{assert(ok,name);tests.push({name,status:'PASS'});};
(async()=>{const browser=await chromium.connectOverCDP(process.env.AGENT_BROWSER_CDP),p=browser.contexts().flatMap(c=>c.pages()).find(p=>p.url().startsWith(URL));if(!p)throw Error('live v04 tab missing');const c=p.context();p.on('pageerror',e=>errors.push(e.message));await p.waitForFunction(()=>window.__oratorioReview);const saved=await p.evaluate(()=>Object.fromEntries(Object.entries(localStorage)));try{
 if(await p.locator('[data-part="T"]').count()){await p.locator('[data-part="T"]').click();await p.locator('#first-next').click();}else{await p.locator('[data-route="home"]').first().click();}
 await p.locator('[data-open="NO01"]').click();await p.locator('section [data-route="practice"]').click();await p.waitForSelector('[data-score-cue="CUE-N01-01"]');check('HTTPS v04 실제 셸과 첫 앵커',await p.evaluate(()=>ORATORIO_BUNDLE.config.build==='unified-internal-v0.4.0'));
 await p.locator('#play').click();await p.waitForFunction(()=>__oratorioReview.playing);const gen=await p.evaluate(()=>__oratorioReview.playGeneration);await p.locator('[data-score-page="8"]').click();await p.waitForSelector('[data-score-cue="CUE-N01-02"]');check('배포8쪽 이미지와 마커',await p.locator('#score-image').evaluate(i=>i.complete&&i.naturalWidth>0));await p.locator('[data-score-cue="CUE-N01-02"]').click();check('배포 악보 터치 원문과 대조 경고',await p.locator('#narrative-dialog').evaluate(d=>d.open&&d.textContent.includes('m14')&&d.textContent.includes('m16')));check('배포 페이지·터치 후 음악 유지',await p.evaluate(g=>__oratorioReview.playing&&__oratorioReview.playGeneration===g&&__oratorioReview.sourceCount===2,gen));await p.keyboard.press('Escape');check('배포 팝업 닫기·초점 복귀',await p.evaluate(()=>document.activeElement.dataset.scoreCue==='CUE-N01-02'));
 await p.locator('[data-zoom="크게"]').click();check('배포 확대에도 음악 유지',await p.evaluate(g=>__oratorioReview.playGeneration===g&&__oratorioReview.playing,gen));await p.locator('#play').click();await p.locator('[data-action="library"]').click();await p.locator('#package-save').click();await p.waitForFunction(()=>!OratorioOffline.busy&&OratorioOffline.activeValid,{timeout:60000});check('배포자료8개 무결성 검증 후 저장',await p.evaluate(async()=>{const a=OratorioOffline.registry.active;return a.manifest.items.length===8&&(await (await caches.open(a.cache)).keys()).length===8;}));await p.locator('#library-close').click();await c.setOffline(true);check('네트워크 차단 직접 확인',await p.evaluate(async()=>{try{await fetch('package.json?nevercached='+Date.now());return false;}catch{return true;}}));await p.reload();await p.waitForFunction(()=>window.__oratorioReview);await p.locator('[data-action="resume"]').click();await p.locator('[data-score-page="8"]').click();await p.waitForSelector('[data-score-cue="CUE-N01-02"]');check('HTTPS 오프라인 재실행8쪽 표시',await p.locator('#score-image').evaluate(i=>i.complete&&i.naturalWidth>0));await p.locator('[data-score-cue="CUE-N01-02"]').click();check('오프라인 악보 터치 원문 열람',await p.locator('#narrative-dialog').evaluate(d=>d.open&&d.textContent.includes('CUE-N01-02')));await p.locator('[data-narrative-action="close"]').click();await p.locator('#play').click();await p.waitForFunction(()=>__oratorioReview.playing);check('HTTPS 오프라인 음악 실제재생',await p.evaluate(()=>__oratorioReview.audioDecoded&&__oratorioReview.sourceCount===2));await p.locator('#play').click();check('배포 브라우저JS예외 없음',errors.length===0);
 }finally{await c.setOffline(false);await p.evaluate(s=>{Object.keys(localStorage).forEach(k=>{if(k.startsWith('oratorio.')&&!(k in s))localStorage.removeItem(k);});for(const [k,v] of Object.entries(s))if(k.startsWith('oratorio.'))localStorage.setItem(k,v);},saved);}
 await p.screenshot({path:ROOT+'/qa/github-live-score.png',fullPage:true});fs.writeFileSync(ROOT+'/qa/github-live-report.json',JSON.stringify({url:URL,tests,errors,environment:'shared Chromium HTTPS; network offline reload; not physical tablet'},null,2));console.log(JSON.stringify({passed:tests.length,errors}));process.exit(0);
})().catch(e=>{console.error(e.stack);process.exit(1)});
