const {chromium}=require('/vercel/sandbox/node_modules/playwright');const fs=require('fs'),assert=require('assert'),crypto=require('crypto');
const ROOT='/data/oratorio_v04',BASE='http://localhost:8775/app/v04/',tests=[],errors=[];const check=(name,ok)=>{assert(ok,name);tests.push({name,status:'PASS'});};
(async()=>{const b=await chromium.launch({executablePath:'/usr/local/bin/chromium',headless:true,args:['--no-sandbox']});const c=await b.newContext({viewport:{width:1180,height:820},hasTouch:true});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(BASE);await p.waitForFunction(()=>window.__oratorioReview);await p.locator('[data-part="T"]').click();await p.locator('#first-next').click();await p.locator('[data-open="NO01"]').click();await p.locator('section [data-route="practice"]').click();
 await p.waitForSelector('[data-score-cue="CUE-N01-01"]');check('7쪽 m1 후보 앵커 표시',await p.locator('[data-score-cue]').getAttribute('aria-label').then(t=>t.includes('m1')&&t.includes('후보')));
 await p.locator('#play').click();await p.waitForFunction(()=>__oratorioReview.playing);const gen=await p.evaluate(()=>__oratorioReview.playGeneration);
 await p.locator('[data-score-page="8"]').tap();await p.waitForSelector('[data-score-cue="CUE-N01-02"]');check('8쪽 표시·음악 엔진 유지',await p.evaluate(g=>__oratorioReview.scorePage===8&&__oratorioReview.playing&&__oratorioReview.playGeneration===g,gen));check('8쪽 실제 이미지 decode',await p.locator('#score-image').evaluate(i=>i.complete&&i.naturalWidth>0&&i.src.includes('page8')));
 await p.locator('[data-score-cue="CUE-N01-02"]').tap();check('악보 마커 터치로 정확한 Cue 열기',await p.locator('#narrative-dialog').evaluate(d=>d.open&&d.textContent.includes('CUE-N01-02')));check('악보 터치 중 음악 이동·중지 없음',await p.evaluate(g=>__oratorioReview.playing&&__oratorioReview.playGeneration===g&&__oratorioReview.state.from===1&&__oratorioReview.state.to===3,gen));check('원문14와 관찰16·ff 미확인 명시',await p.locator('#narrative-dialog .mapping-warning').textContent().then(t=>t.includes('m14')&&t.includes('m16')&&t.includes('ff')&&t.includes('확인하지 못')));check('원문 m14 보존',await p.locator('.source-full').textContent().then(t=>t.includes('m.14')));await p.keyboard.press('Escape');check('마커 팝업 Escape·초점 복귀',await p.locator('#narrative-dialog').evaluate(d=>!d.open)&&await p.evaluate(()=>document.activeElement.dataset.scoreCue==='CUE-N01-02'));
 for(const z of ['보통','크게','전체 페이지']){await p.locator(`[data-zoom="${z}"]`).tap();await p.waitForTimeout(120);check(z+' 표시 중 음악 유지',await p.evaluate(g=>__oratorioReview.playing&&__oratorioReview.playGeneration===g,gen));}
 await p.locator('#play').click();
 for(const [w,h] of [[1180,820],[820,1180],[390,844]]){await p.setViewportSize({width:w,height:h});for(const page of [7,8]){await p.locator(`[data-score-page="${page}"]`).click();for(const z of ['보통','크게','전체 페이지']){await p.locator(`[data-zoom="${z}"]`).click();await p.waitForFunction(()=>document.querySelector('#score-image').complete&&document.querySelector('#score-image').naturalWidth>0);await p.waitForTimeout(130);
 check(`${w} p${page} ${z}: 이미지·좌표·44px 버튼`,await p.evaluate(()=>{const img=document.querySelector('#score-image'),o=document.querySelector('#no01-score-overlay').getBoundingClientRect(),m=document.querySelector('[data-score-cue]').getBoundingClientRect(),r=document.querySelector('.anchor-box').getBoundingClientRect(),a=ORATORIO_BUNDLE.narrativeReview.scoreAudit.anchors.find(a=>a.printedPage===__oratorioReview.scorePage);const meta=ORATORIO_BUNDLE.narrativeReview.pages[String(a.printedPage)];let x=a.normalizedRect.x,y=a.normalizedRect.y;if(__oratorioReview.state.zoom==='크게'){x=(x*meta.fullSize[0]-meta.cropPixels[0])/(meta.cropPixels[2]-meta.cropPixels[0]);y=(y*meta.fullSize[1]-meta.cropPixels[1])/(meta.cropPixels[3]-meta.cropPixels[1]);}return img.complete&&Math.abs(r.left-(o.left+x*o.width))<1&&Math.abs(r.top-(o.top+y*o.height))<1&&m.width>=44&&m.height>=44&&m.left>=o.left-1&&m.right<=o.right+1&&m.top>=o.top-1&&m.bottom<=o.bottom+1;}));
 check(`${w} p${page} ${z}: 가로 넘침 없음`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 if(page===8){await p.locator('[data-zoom="크게"]').click();await p.waitForTimeout(200);await p.screenshot({path:ROOT+`/qa/score-p8-${w}x${h}.png`,fullPage:true});if(w===1180){let html=await p.evaluate(()=>document.documentElement.outerHTML);html=html.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<link[^>]*rel="(?:manifest|icon|apple-touch-icon)"[^>]*>/gi,'').replace(/<link[^>]*href="styles.css"[^>]*>/,'<style>'+fs.readFileSync(ROOT+'/app/v04/styles.css','utf8')+'</style>');html=html.replace(/src="http:\/\/localhost:8775\/app\/assets\/([^"?]+)[^"]*"/g,(_,x)=>`src="data:image/png;base64,${fs.readFileSync(ROOT+'/app/assets/'+x).toString('base64')}"`);fs.writeFileSync(ROOT+'/qa/score-preview.html',html);}}
 }}
 await p.locator('[data-score-cue="CUE-N01-02"]').dispatchEvent('pointerdown',{pointerId:4,clientX:20,clientY:20});await p.locator('[data-score-cue="CUE-N01-02"]').dispatchEvent('pointermove',{pointerId:4,clientX:50,clientY:70});await p.locator('[data-score-cue="CUE-N01-02"]').dispatchEvent('pointerup',{pointerId:4});await p.locator('[data-score-cue="CUE-N01-02"]').dispatchEvent('click');check('드래그 뒤 잘못된 팝업 차단',await p.locator('#narrative-dialog').evaluate(d=>!d.open));await p.locator('[data-score-cue="CUE-N01-02"]').tap();check('새 탭으로 후보 팝업 정상 열림',await p.locator('#narrative-dialog').evaluate(d=>d.open));await p.screenshot({path:ROOT+'/qa/score-dialog-phone.png'});await p.locator('[data-narrative-action="close"]').click();
 await p.locator('[data-narrative-stage="isolation"]').tap();check('수동 단계로7쪽 연결',await p.evaluate(()=>__oratorioReview.scorePage===7));await p.locator('[data-narrative-stage="revelation"]').tap();check('수동 단계로8쪽 연결·Cue반복 잠금',await p.evaluate(()=>__oratorioReview.scorePage===8)&&await p.locator('.narrative-actions button[disabled]').isDisabled());
 const data=JSON.parse(fs.readFileSync(ROOT+'/app/v04/data/content-v01.json'));check('좌표는 후보·음원 시간은 null',data.narrativeReview.scoreAudit.anchors.every(a=>a.status==='VISUALLY_CHECKED_CANDIDATE'&&a.timeRange===null)&&data.narrativeReview.autoFollow===false);const old=JSON.parse(fs.readFileSync('/data/oratorio_v03/app/v03/data/content-v01.json'));check('기존 두 음원 해시 불변',['tenor','piano'].every(k=>data.config.assets[k].sha256===old.config.assets[k].sha256));check('새 패키지8개 모두 해시 일치',JSON.parse(fs.readFileSync(ROOT+'/app/v04/package.json')).items.every(a=>crypto.createHash('sha256').update(fs.readFileSync(require('path').resolve(ROOT+'/app/v04',a.url))).digest('hex')===a.sha256));
 await p.locator('[data-action="library"]').click();await p.locator('#package-save').click();await p.waitForFunction(()=>!OratorioOffline.busy&&OratorioOffline.activeValid);await p.locator('#library-close').click();await c.setOffline(true);await p.reload();await p.waitForFunction(()=>window.__oratorioReview);await p.locator('[data-action="resume"]').click();await p.locator('[data-score-page="8"]').click();await p.waitForSelector('[data-score-cue="CUE-N01-02"]');check('오프라인8쪽 이미지 decode',await p.locator('#score-image').evaluate(i=>i.complete&&i.naturalWidth>0));await p.locator('[data-score-cue="CUE-N01-02"]').click();check('오프라인 악보터치 원문 열람',await p.locator('#narrative-dialog').evaluate(d=>d.open&&d.textContent.includes('m16')));await p.locator('[data-narrative-action="close"]').click();await p.locator('#play').click();await p.waitForFunction(()=>__oratorioReview.playing);check('오프라인8쪽과음악 함께 재생',await p.evaluate(()=>__oratorioReview.audioDecoded&&__oratorioReview.sourceCount===2));check('새 악보터치 JS예외 없음',errors.length===0);
 fs.writeFileSync(ROOT+'/qa/score-report.json',JSON.stringify({tests,errors,environment:'Chromium touch-enabled emulator; actual iPad/Safari not tested',sourcePdfSha256:data.narrativeReview.scoreAudit.source.pdfSha256},null,2));console.log(JSON.stringify({passed:tests.length,errors}));await b.close();process.exit(0);})().catch(e=>{console.error(e.stack);process.exit(1)});
